name: Maven CI
on:
  push:
    branches:
      - main
      - 'releases/[1-9]+.[0-9]+.x'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - '**/README.md'
  pull_request:
    branches:
      - main
      - 'releases/[1-9]+.[0-9]+.x'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - '**/README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Setup Maven Dependencies Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 22.0.0.2
          java-version: 17
          components: 'native-image'
      - name: Set Maven Project Version
        shell: bash
        run: |
          BUILD_VERSION=$(./mvnw -D expression=project.version -q -D forceStdout help:evaluate | tail -1 | tr -d '\r\n')
          [[ "$BUILD_VERSION" != *"-SNAPSHOT" ]] && BUILD_VERSION="${BUILD_VERSION}-SNAPSHOT" && ./mvnw --batch-mode -D generateBackupPoms=false -D updateMatchingVersions=false -D processAllModules=true -D newVersion=$BUILD_VERSION org.codehaus.mojo:versions-maven-plugin:2.9.0:versions:set || true
      - name: Build Maven Project
        if: success() && (github.event_name == 'pull_request' || (github.event_name == 'push'))
        run: ./mvnw --batch-mode -D ci.build -D nativeImage install
      - name: Smoke Test
        if: success()
        run: |
          java -jar target/java-cli-template-*.jar --help
          ./target/app --help
      - name: Publish Github Pages
        if: success()
        continue-on-error: true
        uses: jamesives/github-pages-deploy-action@v4.2.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: gh-pages